image: openbsd/7.3
packages:
  - go
  - git
  - sassc
secrets:
  - 8ad6a3b8-827a-4454-8337-3ec2baab7ca0
sources:
  - ssh://git@git.sr.ht/~aqtrans/gowiki
environment:
  project: gowiki
  remote: deploy@starbuck.squanch.space
tasks:
  - setup: |
      cd ${project}
      go get -d
      go generate
  - test: |
      cd ${project}
      go test
      go test -race
      go test -cover
      go test -bench=.
  - scss: |
      cd ${project}
      sassc -t compressed scss/grid.scss assets/css/wiki.css
  - build: |
      cd ${project}
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o gowiki
  - deploy: |
      cd ${project}
      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no gowiki $remote:/tmp/gowiki
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $remote "doas /bin/mv /tmp/gowiki /usr/local/bin/gowiki"
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $remote "doas /usr/sbin/rcctl restart gowiki"
  - mirror-to-github: |
      cd ${project}
      ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
      echo -e "Host github.com\n    IdentityFile ~/.ssh/id_rsa\n    IdentitiesOnly yes\n    BatchMode yes\n" >> ~/.ssh/config
      git remote add github git@github.com:aqtrans/gowiki.git
      git push --prune github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/* master
