image: openbsd/7.3
packages:
  - go
  - git
  - sassc
secrets:
  - 1efbd7f2-d0b5-4cfc-8a0c-f1c12da95d4e
sources:
  - ssh://git@git.squanch.space/~aqtrans/gowiki
tasks:
  - setup: |
      cd gowiki
      go get -d
      go generate
  - test: |
      cd gowiki
      go test
      go test -race
      go test -cover
      go test -bench=.
  - scss: |
      cd gowiki
      sassc -t compressed scss/grid.scss assets/css/wiki.css
  - build: |
      cd gowiki
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o gowiki
  - deploy: |
      cd gowiki
      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no gowiki deploy@morty.squanch.space:/tmp/gowiki
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@morty.squanch.space "doas /bin/mv /tmp/gowiki /usr/local/bin/gowiki"
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@morty.squanch.space "doas /usr/sbin/rcctl restart gowiki"
