image: openbsd/7.6
packages:
  - go
  - git
  - sassc
secrets:
  - dfbc7cb0-b02f-44ab-9b11-cf1a5467c3d2
sources:
  - ssh://git@git.jba.io:go/wiki.git
environment:
  project: gowiki
  remote: deploy@barry.squanch.space
triggers:
  - action: email
    condition: failure
    to: Jordan Anderson <jordan@jba.io>
tasks:
  - setup: |
      cd ${project}
      go get -d
      go generate
  - test: |
      cd ${project}
      go test
      go test -cover
      go test -bench=.
  - scss: |
      cd ${project}
      sassc -t compressed scss/grid.scss assets/css/wiki.css
  - build: |
      cd ${project}
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o gowiki
      if [ "$(git rev-parse origin/master)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - deploy: |
      cd ${project}
      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no gowiki $remote:/tmp/gowiki
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $remote "doas /bin/mv /tmp/gowiki /usr/local/bin/gowiki"
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $remote "doas /usr/sbin/rcctl restart gowiki"
