variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  PROD_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - deploy

build-image:
  stage: build
  script:
    - docker build --pull -t $IMAGE_TAG .

test-my-project:
  stage: test
  coverage: '/coverage: \d+\.\d+/'
  script:
    - docker pull $IMAGE_TAG
    - docker run $IMAGE_TAG go get -d  
    - docker run $IMAGE_TAG go get -v
    - docker run $IMAGE_TAG go get -race
    - docker run $IMAGE_TAG go get -cover

deploy_staging:
  stage: deploy
  script:
    - docker pull $IMAGE_TAG
    - docker push $IMAGE_TAG
  environment:
    name: staging
    url: https://gowiki.lisa.es.gy
  when: manual

deploy_prod:
  stage: deploy
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $PROD_TAG
    - docker push $PROD_TAG
  environment:
    name: production
    url: https://wiki.jba.io
  only:
    - master@go/wiki