# See docs/examples here:
# http://doc.gitlab.com/ce/ci/quick_start/README.html
# http://doc.gitlab.com/ce/ci/yaml/README.html

# GitLab CI template for Go tests. Note this installs
# a new working copy of Go (1.5.2 in this case) 
# in a non-standard path such that sudo/root is not 
# needed for the install stage.

# note that this particular install-environment stage
# is overly verbose in order to debug anything tricky
# or weird in your environment - feel free to trim it 
# down as needed

stages:
  - install-environment
  - build
  - deploy  

install-go:
  stage: install-environment
  script:
    - export CURRENT_BUILD_PATH=$(pwd)
    - echo $PATH
    - echo $CURRENT_BUILD_PATH
    - rm -rf $HOME/gopath
    #- mkdir -p $HOME/gopath # for GOPATH (contains code and external packages)
    - mkdir -p $HOME/gopath/src
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOPATH/bin
    - ln -s $CI_PROJECT_DIR $GOPATH/src/wiki
    - go version
    - echo $PATH
    - go env
    - which go

build-my-project:
  stage: build
  script:
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOPATH/bin
    - cd $GOPATH/src/wiki
    - go get -d  
    - go build

deploy-it:
  stage: deploy
  script:
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
    - cd $GOPATH/src/wiki
    - mkdir deploy
    - go get -d
    - go build -o ./deploy/wiki
    - cp -r templates README.md assets deploy/
    - rsync -av --delete --exclude auth.db --exclude conf.json --exclude md --exclude uploads --exclude http.log deploy/ golang@localhost:/home/golang/wiki/
    #- ssh golang@localhost sudo systemctl restart golang-wiki
