variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  PROD_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - deploy

build-image:
  stage: build
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test-my-project:
  stage: test
  coverage: '/coverage: \d+\.\d+/'
  script:
    - docker pull $IMAGE_TAG  
    #- git clone git@jba.io:aqtrans/gowiki-testdata.git 
    - docker run $IMAGE_TAG go get -d  
    - docker run -e "GOWIKI_GITREPO=https://aqtrans:mC\$p1cy89@git.jba.io/aqtrans/gowiki-testdata.git" $IMAGE_TAG go test -v
    - docker run -e "GOWIKI_GITREPO=https://aqtrans:mC\$p1cy89@git.jba.io/aqtrans/gowiki-testdata.git" $IMAGE_TAG go test -race
    - docker run -e "GOWIKI_GITREPO=https://aqtrans:mC\$p1cy89@git.jba.io/aqtrans/gowiki-testdata.git" $IMAGE_TAG go test -cover
    #- docker run -v $CI_PROJECT_DIR/gowiki-testdata:/go/src/wiki/tests/gowiki-testdata $IMAGE_TAG ls -la /go/src/wiki/tests/gowiki-testdata
    #- docker run -v $CI_PROJECT_DIR/gowiki-testdata:/go/src/wiki/tests/gowiki-testdata $IMAGE_TAG ls -la /go/src/wiki/tests    
    #- docker run -v $CI_PROJECT_DIR/gowiki-testdata:/go/src/wiki/tests/gowiki-testdata $IMAGE_TAG go test -v
    #- docker run -v $CI_PROJECT_DIR/gowiki-testdata:/go/src/wiki/tests/gowiki-testdata $IMAGE_TAG go test -race
    #- docker run -v $CI_PROJECT_DIR/gowiki-testdata:/go/src/wiki/tests/gowiki-testdata $IMAGE_TAG go test -cover

deploy_staging:
  stage: deploy
  script:
    - docker pull $IMAGE_TAG
    - docker push $IMAGE_TAG
  environment:
    name: staging
    url: https://gowiki.lisa.es.gy
  when: manual

deploy_prod:
  stage: deploy
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $PROD_TAG
    - docker push $PROD_TAG
  environment:
    name: production
    url: https://wiki.jba.io
  only:
    - master@go/wiki