image: golang:latest
# See docs/examples here:
# http://doc.gitlab.com/ce/ci/quick_start/README.html
# http://doc.gitlab.com/ce/ci/yaml/README.html

# GitLab CI template for Go tests. Note this installs
# a new working copy of Go (1.5.2 in this case) 
# in a non-standard path such that sudo/root is not 
# needed for the install stage.

# note that this particular install-environment stage
# is overly verbose in order to debug anything tricky
# or weird in your environment - feel free to trim it 
# down as needed

before_script:
  - ln -s /builds /go/src/jba.io
  - cd /go/src/jba.io/go/wiki

stages:
  - install-environment
  - build
  - test
  - deploy  

install-go:
  stage: install-environment
  script:
    - go version
    - echo $PATH
    - go env
    - which go
    - go get -u github.com/golang/dep/...
    - go get github.com/GeertJohan/go.rice/rice

build-my-project:
  stage: build
  script:
    - cd $GOPATH/src/wiki
    - dep ensure
    - go get -d
    - go get github.com/GeertJohan/go.rice/rice
    - rice embed-go
    - go build

test-my-project:
  stage: test
  script:
    - cd $GOPATH/src/wiki
    - dep ensure    
    - go test -v
    - go test -race 

deploy-it:
  stage: deploy
  only: 
    - master@go/wiki
  script:
    - cd $GOPATH/src/wiki
    - mkdir deploy
    - dep ensure    
    - go get -d
    - go get github.com/GeertJohan/go.rice/rice
    - npm install
    - npm install bower
    - node_modules/.bin/bower install
    - npm build
    - node_modules/.bin/gulp sass
    - rice embed-go
    - go build -o ./deploy/wiki
    - cp -r README.md deploy/
