#GitPath = /usr/bin/git
#GitCommitEmail = "wiki@example.com"
#GitCommitName = "Golang Wiki"
Domain = "wiki.example.com"
Port = "8000"
DataDir = "/var/lib/gowiki/"
WikiDir = "/var/lib/gowiki/wikidata/"
RemoteGitRepo = ""
PushOnSave = true
DevMode = false
InitWikiRepo = false
CacheEnabled = true
#RavenDSN = "sentry.io/"
