#!/bin/sh

set -e

USER=gowiki

if ! getent passwd "$USER" >/dev/null; then
 adduser --quiet --system --home /var/lib/gowiki "$USER"
fi

systemctl --system daemon-reload >/dev/null
deb-systemd-helper start gowiki.service >/dev/null 
