#!/bin/sh

set -e

USER=gowiki

if ! getent passwd "$USER" >/dev/null; then
 adduser --quiet --system --shell /bin/bash --home /var/lib/gowiki --group "$USER"
fi

systemctl --system daemon-reload >/dev/null
#systemctl start gowiki.service >/dev/null 